name: Run Feeds Assembler

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours (0,6,12,18 UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetches your code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest Python 3 version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Fetch and Assemble Feeds
        run: python scripts/feedsAssembler.py
